### ISSUE TITLE
Remove workaround for floating-ips

### ISSUE THREAD

**Issue by fwiesel** [sapcc/nova#25]
The change 72d2dbd2a738bf90a1ea3f467c3be931f2603ce6 is superfluous with later releases of ironic.

Undo it, as soon as the other work-around have been removed.

**Comment by grandchild** [comment]
I think this is well outdated, no?

**Comment by joker-official** [comment]
Did you check we reverted that commit?

**Comment by grandchild** [comment]
The lines that were removed in that commit are present in stable/queens-m3.
